ocp-power-automation/openshift-install-power

README.md
=> Update the script url in README

.github/workflows/cygwin.yml, deploy.sh
=> debug control switches, sensitive data hide and state file check

README.md, deploy.sh
=> Change the retry func to use lock file

deploy.sh
=> pull-secret and ssh-key interaction enhancements

deploy.sh
=> Log file write check

deploy.sh
=> Fix the wait issue on LOGFILE getting updated

deploy.sh
=> Fix LOGFILE typo

deploy.sh
=> Fix the retry attempts on versbose

deploy.sh
=> output formatting and questions placement

deploy.sh
=> Added progress bar

deploy.sh
=> Not display progress bar when verbose is enabled

deploy.sh
=> Handle condition when no logs

deploy.sh
=> machine processor check

deploy.sh
=> Cli login and capturing service_instance_id during create

deploy.sh
=> Handle unknown errors during provisioning

deploy.sh
=> Fix re-apply issue and reduce sleep time between retry

deploy.sh
=> Read API key from var file if given

deploy.sh
=> refactor cluster access info code

deploy.sh
Adding `--no-region`to the login command, else CLI waiting for the user input.
=> logging into the cloud without specifying a region

deploy.sh
=> Fix lsof command not found error

deploy.sh
deploy.sh updated to display user password & pull-secret with asterisk.
=> Password and pullsecret displayed asterisk

deploy.sh
=> Proper check for API key in var file

deploy.sh
=> Fix the grep issue during delete_failed_instance

deploy.sh
=> Initial ping and ssh test for monitoring progress

deploy.sh
=> Fix the bastion ssh cmd o/p issue

deploy.sh
=> Change the monitor function

deploy.sh
=> Muliple improvements

deploy.sh
=> Add support for node reboot and multiple fixes

deploy.sh
=> Fix the bootstrap node name

deploy.sh
=> Remove use of mapfile as not availbale in old bash

deploy.sh
=> Fixed the cluster info for non-root user

.github/workflows/cygwin.yml, .github/workflows/main.yml
=> Change GH Actions to run on devel

deploy.sh
=> Setting TF version to v0.13.5

deploy.sh
=> Fix name for bootstrap in delete_failed_instance

README.md, docs/create.md, docs/destroy.md, docs/setup.md, docs/variables.md
=> Update the docs

README.md
=> Include the new env variable

deploy.sh
=> Add bastion to delete_failed_instance

deploy.sh
Refactoring of code for verify_data, precheck and setup functions
=> Refactoring of code for verify_data, precheck and setup functions

deploy.sh
=>  destroy function checks and support force-destroy

deploy.sh
=> Handle bastion delete in BUILD status

.github/workflows/cygwin.yml, .github/workflows/main.yml, README.md, docs/create.md, docs/destroy.md, docs/setup.md, docs/variables.md, openshift-install-powervs
=> Rename the script

openshift-install-powervs
=> ssh key verify code update

openshift-install-powervs
=> update mac deps

openshift-install-powervs
=> x86_64 machine check

README.md, docs/variables.md, openshift-install-powervs
=> Ignore RHEL images during RHCOS prompt and vv

openshift-install-powervs
=> Handle pasting of large secrets (pull-secret)

README.md, openshift-install-powervs
=> support for access-info action

openshift-install-powervs
=> check for windows packages

README.md, docs/setup.md, openshift-install-powervs
=> Add tar package to install list

openshift-install-powervs
=> Add prompt for bastion HA

openshift-install-powervs
=> Change name to id for ibmcloud pi instance

openshift-install-powervs
=> Spelling fixes

openshift-install-powervs
=> Update default configs and associated messages

openshift-install-powervs
=> Fix access-info for wildcard domains

openshift-install-powervs
=> Fix the plan failure due to vars expansion

openshift-install-powervs
=> windows CI fix

openshift-install-powervs
=> Download OC CLI

README.md
=> Misc updates including firewall requirements

openshift-install-powervs
=> Display client only version during setup

openshift-install-powervs
=> Ignore commented values from var file

openshift-install-powervs
=> RHCOS image filter based on RELEASE_VER

openshift-install-powervs
=> Delete bootstrap node after install

openshift-install-powervs
=> Support for DNS entries in access-info

openshift-install-powervs
=> Handle stale public network

README.md
=> Document use single quotes for special characters

openshift-install-powervs
=> Fix the service instance name with spaces

openshift-install-powervs
=> Fix the bastion count when HA is selected

openshift-install-powervs
=> Validate the service instance id for invalid and power-iaas specific

openshift-install-powervs
=> color highlight for access-info

openshift-install-powervs
=> Optionally use ARTIFACTS_REPO from env

openshift-install-powervs
=> Reverse ocp release to show latest on top

openshift-install-powervs
=> Add retry while deleting bootstrap node

openshift-install-powervs
=> Fix the Terraform retry iterator issue

openshift-install-powervs
=> Fix the bootstrap delete cmd

openshift-install-powervs
=>  refactor var, varfile function

openshift-install-powervs
=> Fix the variables for no private network

README.md
Added a quick link to the pre-req README.md so that people following this README can ensure they meet all the pre-req before going ahead with the install process
Signed-off-by: Deepak Shetty <dpkshetty@gmail.com>
=> Add link to the pre-req

CONTRIBUTING.md, DCO1.1.txt, README.md
=> Misc updates to doc

openshift-install-powervs
=> platform checks

openshift-install-powervs
=> dependency packages checks

openshift-install-powervs
=> Support simultaneous deployments in different regions

openshift-install-powervs
=> Fix the bootstrap destroy with new code in 4.6

README.md, docs/setup.md, openshift-install-powervs
=>  Update the default OCP version to 4.7 and check for artifacts version

openshift-install-powervs
=> Include catalog images for selection

openshift-install-powervs
=> Check for lock file even after a minute

openshift-install-powervs
=> Fix check for var option

images/Dockerfile
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>
=> Container image with installer script and dependencies

openshift-install-powervs
=> Not display any log during output

openshift-install-powervs
Reverts ocp-power-automation/openshift-install-power#143
=> Revert "Not display any log during output"

openshift-install-powervs
=> Clean state after destroy and not delete existing variable file until the command is completed

images/Dockerfile
=> Reduce RUN steps

openshift-install-powervs
=> Allow reading options even when unsupported platform

docs/variables.md, openshift-install-powervs
Fixes: #149
Signed-off-by: Prajyot Parab <Prajyot.Parab1@ibm.com>
=> Accept system_type via interactive mode

README.md, docs/create.md, docs/flavor.md, docs/variables.md, openshift-install-powervs
Fixes: #127
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>
=> Flavor template feature

.travis.yml
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>
=> Travis config for creating and publishing multi arch images

docs/variables.md, openshift-install-powervs
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>
=> Flavor template fix

docs/variables.md, openshift-install-powervs
Signed-off-by: Prajyot Parab <Prajyot.Parab1@ibm.com>
=> Support usage of IBM Cloud services

openshift-install-powervs
Ref: https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html
Signed-off-by: Rafael Sene  <rpsene@br.ibm.com>
=> Change error return code to 1

openshift-install-powervs
Signed-off-by: Prajyot Parab <Prajyot.Parab1@ibm.com>
Fixes #176
=> flavor bugfix

.github/workflows/main.yml, openshift-install-powervs
=> Align with new ibmcloud release references

.github/workflows/main.yml, openshift-install-powervs
=> Limit verbose from new versions of ibmcloud

docs/variables.md, openshift-install-powervs
Signed-off-by:  Aishwarya Kamat <aishwarya.kamat@ibm.com>
=> Allow setting the vpc region

openshift-install-powervs
Modified the expression as per the change in the output of curl command for fetching ALL_OCP_VERSIONS.
=> Updated expression as per curl output

openshift-install-powervs
=> Check for script version to update

openshift-install-powervs
=> Filtering the required versions from the curl output

README.md, openshift-install-powervs
=> Use the OCP 4.10 version as default

openshift-install-powervs
=> Use latest Terraform and change power path

.gitignore, openshift-install-powervs
1. Replace tac command with tail -f
2. Added .gitignore
=> Remove tac command usage which require coreutils

.github/workflows/main.yml, README.md, openshift-install-powervs
=> Support running on macOS Monterey and Ubuntu 22.04

openshift-install-powervs
=> Fix for coreutils conflict on ubi8

openshift-install-powervs
=> fix reboot node ignored

openshift-install-powervs
=> add raw option to output commands and some refactoring

openshift-install-powervs
- Add support for OSX #206
- Add support for ARCH arm64 #206
Signed-off-by: Paul Bastide <pbastide@us.ibm.com>
=> Support for latest OSX and arm64 Arches #206

openshift-install-powervs
=> add a flag to ignore warning messages

README.md, openshift-install-powervs
=> Use default ocp 4.12

openshift-install-powervs
=> Support all future macos releases
